In [1]:
import pandas as pd

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

In [ ]:
# !pip install mlxtend

In [35]:
df = pd.read_csv('dataset.csv',header=None)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1499 entries, 0 to 1498
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1499 non-null   object
 1   1       1499 non-null   object
 2   2       1499 non-null   object
 3   3       1499 non-null   object
 4   4       1499 non-null   object
 5   5       1448 non-null   object
 6   6       1411 non-null   object
 7   7       1356 non-null   object
 8   8       1300 non-null   object
 9   9       1241 non-null   object
 10  10      1203 non-null   object
 11  11      1156 non-null   object
 12  12      1103 non-null   object
 13  13      1044 non-null   object
dtypes: object(14)
memory usage: 164.1+ KB

In [37]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,pork,sandwich bags,lunch meat,all- purpose,flour,soda,butter,vegetables,beef,aluminum foil,all- purpose,dinner rolls,shampoo,all- purpose
1,shampoo,hand soap,waffles,vegetables,cheeses,mixes,milk,sandwich bags,laundry detergent,dishwashing liquid/detergent,waffles,individual meals,hand soap,vegetables
2,pork,soap,ice cream,toilet paper,dinner rolls,hand soap,spaghetti sauce,milk,ketchup,sandwich loaves,poultry,toilet paper,ice cream,ketchup
3,juice,lunch meat,soda,toilet paper,all- purpose,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,pasta,tortillas,mixes,hand soap,toilet paper,vegetables,vegetables,paper towels,vegetables,flour,vegetables,pork,poultry,eggs

In [38]:
df.shape

(1499, 14)

In [102]:
ar = df[1].values

In [109]:
bills = df.apply(lambda row: ','.join(row.values.astype(str)).split(','),axis=1)

In [56]:
encoder = TransactionEncoder()

In [59]:
transactions = pd.DataFrame(encoder.fit(bills).transform(bills),columns=encoder.columns_)

In [116]:
del transactions[' ']

In [118]:
transactions.columns

Index([' all- purpose', ' aluminum foil', ' bagels', ' beef', ' butter',
       ' cereals', ' cheeses', ' coffee/tea', ' dinner rolls',
       ' dishwashing liquid/detergent', ' eggs', ' flour', ' fruits',
       ' hand soap', ' ice cream', ' individual meals', ' juice', ' ketchup',
       ' laundry detergent', ' lunch meat', ' milk', ' mixes', ' paper towels',
       ' pasta', ' pork', ' poultry', ' sandwich bags', ' sandwich loaves',
       ' shampoo', ' soap', ' soda', ' spaghetti sauce', ' sugar',
       ' toilet paper', ' tortillas', ' vegetables', ' waffles', ' yogurt',
       'nan'],
      dtype='object')

In [119]:

display(transactions.head())

,all- purpose,aluminum foil,bagels,beef,butter,cereals,cheeses,coffee/tea,dinner rolls,dishwashing liquid/detergent,...,soap,soda,spaghetti sauce,sugar,toilet paper,tortillas,vegetables,waffles,yogurt,nan
0,True,True,False,True,True,False,False,False,True,False,...,False,True,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,True,False,False,True,...,False,False,False,False,False,False,True,True,False,False
2,False,False,False,False,False,False,False,False,True,False,...,True,False,True,False,True,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,False,False,False

In [127]:
frequent_itemsets = fpgrowth(transactions, min_support= 6/len(bills), use_colnames=True, max_len =3)

In [128]:
rules = association_rules(frequent_itemsets, metric="lift",  min_threshold = 1.5)

In [129]:
display(rules.head(20))

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,"( flour, toilet paper)",( soap),0.062708,0.265510,0.025350,0.404255,1.522560,0.008700,1.232893,0.366173
1,( soap),"( flour, toilet paper)",0.265510,0.062708,0.025350,0.095477,1.522560,0.008700,1.036228,0.467279
2,"( mixes, beef)",( pork),0.065377,0.250167,0.025350,0.387755,1.549986,0.008995,1.224728,0.379654
3,( pork),"( mixes, beef)",0.250167,0.065377,0.025350,0.101333,1.549986,0.008995,1.040011,0.473216
4,"( beef, cheeses)",( sandwich bags),0.066711,0.250167,0.025350,0.380000,1.518987,0.008661,1.209408,0.366089
5,( sandwich bags),"( beef, cheeses)",0.250167,0.066711,0.025350,0.101333,1.518987,0.008661,1.038526,0.455656
6,"( dishwashing liquid/detergent, spaghetti sauce)",( fruits),0.061374,0.263509,0.025350,0.413043,1.567474,0.009178,1.254762,0.385703
7,( fruits),"( dishwashing liquid/detergent, spaghetti sauce)",0.263509,0.061374,0.025350,0.096203,1.567474,0.009178,1.038535,0.491562
8,"( juice, mixes)",( ketchup),0.071381,0.250167,0.027352,0.383178,1.531688,0.009494,1.215639,0.373809
9,( ketchup),"( juice, mixes)",0.250167,0.071381,0.027352,0.109333,1.531688,0.009494,1.042611,0.462937
10,"( pork, sandwich loaves)",( juice),0.060707,0.257505,0.024016,0.395604,1.536298,0.008384,1.228492,0.371646
11,( juice),"( pork, sandwich loaves)",0.257505,0.060707,0.024016,0.093264,1.536298,0.008384,1.035906,0.470151
12,"( cheeses, sandwich loaves)",( soap),0.064710,0.265510,0.026017,0.402062,1.514298,0.008836,1.228371,0.363126
13,( soap),"( cheeses, sandwich loaves)",0.265510,0.064710,0.026017,0.097990,1.514298,0.008836,1.036896,0.462400
14,"( yogurt, sandwich loaves)",( juice),0.064043,0.257505,0.026017,0.406250,1.577639,0.009526,1.250518,0.391195
15,( juice),"( yogurt, sandwich loaves)",0.257505,0.064043,0.026017,0.101036,1.577639,0.009526,1.041151,0.493123
16,"( sandwich bags, mixes)",( tortillas),0.070714,0.244163,0.026017,0.367925,1.506882,0.008752,1.195802,0.361975
17,( tortillas),"( sandwich bags, mixes)",0.244163,0.070714,0.026017,0.106557,1.506882,0.008752,1.040118,0.445040
18,"( tortillas, laundry detergent)",( ketchup),0.059373,0.250167,0.022682,0.382022,1.527071,0.007829,1.213366,0.366938
19,( ketchup),"( tortillas, laundry detergent)",0.250167,0.059373,0.022682,0.090667,1.527071,0.007829,1.034414,0.460305

In [130]:
itemsets = apriori(transactions, 
                           use_colnames=True, 
                           verbose=1,
                           low_memory=False,
                           min_support=0.1
                          )

Processing 324 combinations | Sampling itemset size 32

In [131]:
itemsets.sort_values(by='support',ascending = False)

     support                       itemsets
35  0.597065                  ( vegetables)
38  0.303536                          (nan)
25  0.287525                     ( poultry)
36  0.278853                     ( waffles)
2   0.278185                      ( bagels)
..       ...                            ...
67  0.145430        ( vegetables,  shampoo)
52  0.140761      ( vegetables,  hand soap)
65  0.140093  ( sandwich bags,  vegetables)
63  0.138759           ( vegetables,  pork)
76  0.133422             (nan,  vegetables)

[77 rows x 2 columns]

In [134]:
rules = association_rules(itemsets, metric="lift", min_threshold=1)
rules.sort_values(by='confidence',ascending = False).head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
43,( yogurt),( vegetables),0.268179,0.597065,0.176117,0.656716,1.099908,0.015997,1.173768,0.124119
25,( laundry detergent),( vegetables),0.264176,0.597065,0.172782,0.654040,1.095426,0.015052,1.164689,0.118389
14,( eggs),( vegetables),0.268846,0.597065,0.169446,0.630273,1.055619,0.008928,1.089818,0.072062
27,( lunch meat),( vegetables),0.276184,0.597065,0.172115,0.623188,1.043754,0.007215,1.069328,0.057914
7,( cereals),( vegetables),0.273516,0.597065,0.170113,0.621951,1.041681,0.006807,1.065829,0.055078